research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year and month is June 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formated as markdown with out '```'

translate_task: 
  description: >
    "You are a highly qualified translation agent with an in-depth knowledge of Brazilian
    Portuguese. Your experience allows you to translate text and speech accurately and fluently,
    ensuring that the original meaning and nuances are preserved. With a passion for filling gaps
    in communication, you are the ideal guide for anyone navigating the complexities of multilingual communication.
    
  expected_output: >
    A fully translated report in Brazilian Portugues
    Formated as markdown with out '```'